/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SharePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  apiUrl: "https://your-server.example.com",
  autoClipboard: true,
  defaultExpiry: 0
};
var SharePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.autoSyncInterval = null;
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "share-note",
      name: "\u041E\u043F\u0443\u0431\u043B\u0438\u043A\u043E\u0432\u0430\u0442\u044C \u0437\u0430\u043C\u0435\u0442\u043A\u0443",
      callback: () => this.shareCurrentNote()
    });
    this.addCommand({
      id: "share-note-private",
      name: "\u041F\u043E\u0434\u0435\u043B\u0438\u0442\u044C\u0441\u044F \u043F\u0440\u0438\u0432\u0430\u0442\u043D\u043E",
      callback: () => this.sharePrivateNote()
    });
    this.addCommand({
      id: "update-current-note",
      name: "\u041E\u0431\u043D\u043E\u0432\u0438\u0442\u044C \u0442\u0435\u043A\u0443\u0449\u0443\u044E \u0441\u0442\u0430\u0442\u044C\u044E \u043D\u0430 \u0441\u0435\u0440\u0432\u0435\u0440\u0435",
      callback: () => this.updateCurrentNote()
    });
    this.addCommand({
      id: "sync-shared-notes",
      name: "\u0421\u0438\u043D\u0445\u0440\u043E\u043D\u0438\u0437\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u0441\u0442\u0430\u0442\u0443\u0441 \u0441\u0442\u0430\u0442\u0435\u0439",
      callback: () => this.syncSharedNotes()
    });
    this.addCommand({
      id: "auto-update-all",
      name: "\u041E\u0431\u043D\u043E\u0432\u0438\u0442\u044C \u0432\u0441\u0435 \u043E\u043F\u0443\u0431\u043B\u0438\u043A\u043E\u0432\u0430\u043D\u043D\u044B\u0435 \u0441\u0442\u0430\u0442\u044C\u0438",
      callback: () => this.autoUpdateAllNotes()
    });
    this.addRibbonIcon("share", "\u041E\u043F\u0443\u0431\u043B\u0438\u043A\u043E\u0432\u0430\u0442\u044C \u0437\u0430\u043C\u0435\u0442\u043A\u0443", () => {
      this.shareCurrentNote();
    });
    this.addRibbonIcon("lock", "\u041F\u043E\u0434\u0435\u043B\u0438\u0442\u044C\u0441\u044F \u043F\u0440\u0438\u0432\u0430\u0442\u043D\u043E", () => {
      this.sharePrivateNote();
    });
    this.addSettingTab(new ShareSettingTab(this.app, this));
    this.startAutoSync();
    console.log("Share Plugin loaded");
  }
  async shareCurrentNote() {
    await this.shareNoteWithOptions(false);
  }
  async sharePrivateNote() {
    await this.shareNoteWithOptions(true);
  }
  async shareNoteWithOptions(isPrivate) {
    var _a;
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian.Notice("\u041E\u0442\u043A\u0440\u043E\u0439\u0442\u0435 \u0437\u0430\u043C\u0435\u0442\u043A\u0443 \u0434\u043B\u044F \u043F\u0443\u0431\u043B\u0438\u043A\u0430\u0446\u0438\u0438");
      return;
    }
    try {
      const mode = isPrivate ? "\u0421\u043E\u0437\u0434\u0430\u043D\u0438\u0435 \u043F\u0440\u0438\u0432\u0430\u0442\u043D\u043E\u0439 \u0441\u0441\u044B\u043B\u043A\u0438" : "\u041F\u0443\u0431\u043B\u0438\u043A\u0430\u0446\u0438\u044F \u0437\u0430\u043C\u0435\u0442\u043A\u0438";
      new import_obsidian.Notice(`${mode}...`);
      let content = await this.app.vault.read(activeFile);
      const title = activeFile.basename;
      const sourceId = activeFile.path;
      const customCss = this.extractThemeCss();
      const cache = this.app.metadataCache.getFileCache(activeFile);
      const existingShareId = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.share_id;
      content = await this.processImages(content, activeFile);
      const response = await this.shareNote(
        title,
        content,
        sourceId,
        customCss,
        isPrivate,
        existingShareId
      );
      if (response.success) {
        await this.updateNoteFrontmatter(activeFile, response.url, isPrivate, response.id);
        const action = response.isUpdate ? "\u043E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0430" : "\u043E\u043F\u0443\u0431\u043B\u0438\u043A\u043E\u0432\u0430\u043D\u0430";
        const prefix = isPrivate ? "\u{1F512} \u041F\u0440\u0438\u0432\u0430\u0442\u043D\u0430\u044F \u0441\u0441\u044B\u043B\u043A\u0430" : "\u2705 \u0417\u0430\u043C\u0435\u0442\u043A\u0430";
        if (this.settings.autoClipboard) {
          await navigator.clipboard.writeText(response.url);
          new import_obsidian.Notice(`${prefix} ${action}. \u0421\u0441\u044B\u043B\u043A\u0430 \u0441\u043A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u043D\u0430: ${response.url}`, 5e3);
        } else {
          new import_obsidian.Notice(`${prefix} ${action}: ${response.url}`, 5e3);
        }
      } else {
        throw new Error("Server returned success: false");
      }
    } catch (error) {
      console.error("SharePlugin: Share failed", error);
      const errorMsg = error instanceof Error ? error.message : "\u041D\u0435\u0438\u0437\u0432\u0435\u0441\u0442\u043D\u0430\u044F \u043E\u0448\u0438\u0431\u043A\u0430";
      new import_obsidian.Notice(`\u041D\u0435 \u0443\u0434\u0430\u043B\u043E\u0441\u044C \u043E\u043F\u0443\u0431\u043B\u0438\u043A\u043E\u0432\u0430\u0442\u044C: ${errorMsg}`, 7e3);
    }
  }
  /**
   * Находит все ![[image]] в контенте, загружает на сервер, заменяет на ![](url)
   */
  async processImages(content, sourceFile) {
    const imageRegex = /!\[\[([^\]]+\.(png|jpg|jpeg|gif|bmp|svg|webp))\]\]/gi;
    const matches = [...content.matchAll(imageRegex)];
    if (matches.length === 0)
      return content;
    new import_obsidian.Notice(`\u0417\u0430\u0433\u0440\u0443\u0437\u043A\u0430 ${matches.length} \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0439...`);
    let uploaded = 0;
    for (const match of matches) {
      const fullMatch = match[0];
      const filename = match[1];
      try {
        const imageFile = this.resolveImageFile(filename, sourceFile);
        if (!imageFile) {
          console.warn(`SharePlugin: Image not found: ${filename}`);
          continue;
        }
        const imageData = await this.app.vault.readBinary(imageFile);
        const base64 = this.arrayBufferToBase64(imageData);
        const response = await this.uploadImage(filename, base64);
        if (response.success) {
          content = content.replace(fullMatch, `![${filename}](${response.url})`);
          uploaded++;
        }
      } catch (error) {
        console.error(`SharePlugin: Failed to upload image ${filename}`, error);
      }
    }
    if (uploaded > 0) {
      new import_obsidian.Notice(`\u0417\u0430\u0433\u0440\u0443\u0436\u0435\u043D\u043E ${uploaded}/${matches.length} \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0439`);
    }
    return content;
  }
  /**
   * Находит файл изображения в vault по имени.
   * Obsidian ищет в нескольких местах: рядом с файлом, в корне, в Cache/
   */
  resolveImageFile(filename, sourceFile) {
    var _a;
    const sourceDir = ((_a = sourceFile.parent) == null ? void 0 : _a.path) || "";
    const candidates = [
      `${sourceDir}/${filename}`,
      filename,
      `Cache/${filename}`,
      `Attachments/${filename}`
    ];
    for (const path of candidates) {
      const file = this.app.vault.getAbstractFileByPath(path);
      if (file instanceof import_obsidian.TFile)
        return file;
    }
    const allFiles = this.app.vault.getFiles();
    const found = allFiles.find((f) => f.name === filename);
    if (found instanceof import_obsidian.TFile)
      return found;
    return null;
  }
  arrayBufferToBase64(buffer) {
    const bytes = new Uint8Array(buffer);
    let binary = "";
    for (let i = 0; i < bytes.byteLength; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary);
  }
  async uploadImage(filename, base64Data) {
    const url = `${this.settings.apiUrl}/api/images`;
    const response = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ filename, data: base64Data })
    });
    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Image upload failed: HTTP ${response.status}: ${errorText}`);
    }
    return await response.json();
  }
  extractThemeCss() {
    try {
      const bodyStyle = getComputedStyle(document.body);
      const vars = {
        bgPrimary: bodyStyle.getPropertyValue("--background-primary").trim(),
        bgSecondary: bodyStyle.getPropertyValue("--background-secondary").trim(),
        textNormal: bodyStyle.getPropertyValue("--text-normal").trim(),
        textMuted: bodyStyle.getPropertyValue("--text-muted").trim(),
        textAccent: bodyStyle.getPropertyValue("--text-accent").trim(),
        linkColor: bodyStyle.getPropertyValue("--link-color").trim(),
        linkHover: bodyStyle.getPropertyValue("--link-color-hover").trim(),
        codeBackground: bodyStyle.getPropertyValue("--code-background").trim(),
        codeNormal: bodyStyle.getPropertyValue("--code-normal").trim(),
        h1Color: bodyStyle.getPropertyValue("--h1-color").trim(),
        h2Color: bodyStyle.getPropertyValue("--h2-color").trim(),
        h3Color: bodyStyle.getPropertyValue("--h3-color").trim(),
        h4Color: bodyStyle.getPropertyValue("--h4-color").trim(),
        h5Color: bodyStyle.getPropertyValue("--h5-color").trim(),
        h6Color: bodyStyle.getPropertyValue("--h6-color").trim(),
        blockquoteBorder: bodyStyle.getPropertyValue("--blockquote-border").trim(),
        listMarker: bodyStyle.getPropertyValue("--list-marker-color").trim()
      };
      if (!vars.textNormal && !vars.h1Color && !vars.linkColor) {
        console.warn("SharePlugin: No theme CSS variables found");
        return "";
      }
      const cssRules = [];
      if (vars.textNormal) {
        cssRules.push(`.markdown-body { color: ${vars.textNormal} !important; }`);
      }
      if (vars.h1Color)
        cssRules.push(`.markdown-body h1 { color: ${vars.h1Color} !important; }`);
      if (vars.h2Color)
        cssRules.push(`.markdown-body h2 { color: ${vars.h2Color} !important; }`);
      if (vars.h3Color)
        cssRules.push(`.markdown-body h3 { color: ${vars.h3Color} !important; }`);
      if (vars.h4Color)
        cssRules.push(`.markdown-body h4 { color: ${vars.h4Color} !important; }`);
      if (vars.h5Color)
        cssRules.push(`.markdown-body h5 { color: ${vars.h5Color} !important; }`);
      if (vars.h6Color)
        cssRules.push(`.markdown-body h6 { color: ${vars.h6Color} !important; }`);
      if (vars.linkColor) {
        cssRules.push(`.markdown-body a { color: ${vars.linkColor} !important; }`);
      }
      if (vars.linkHover) {
        cssRules.push(`.markdown-body a:hover { color: ${vars.linkHover} !important; }`);
      }
      if (vars.codeBackground) {
        cssRules.push(`.markdown-body code { background-color: ${vars.codeBackground} !important; }`);
        cssRules.push(`.markdown-body pre { background-color: ${vars.codeBackground} !important; }`);
      }
      if (vars.codeNormal) {
        cssRules.push(`.markdown-body code { color: ${vars.codeNormal} !important; }`);
      }
      if (vars.blockquoteBorder) {
        cssRules.push(`.markdown-body blockquote { border-left-color: ${vars.blockquoteBorder} !important; }`);
      }
      if (vars.textMuted) {
        cssRules.push(`.markdown-body blockquote { color: ${vars.textMuted} !important; }`);
      }
      if (vars.listMarker) {
        cssRules.push(`.markdown-body ul li::marker { color: ${vars.listMarker} !important; }`);
        cssRules.push(`.markdown-body ol li::marker { color: ${vars.listMarker} !important; }`);
      }
      if (vars.textAccent) {
        cssRules.push(`.markdown-body strong { color: ${vars.textAccent} !important; }`);
        cssRules.push(`.markdown-body em { color: ${vars.textAccent} !important; }`);
      }
      return cssRules.join("\n");
    } catch (error) {
      console.error("SharePlugin: Failed to extract theme CSS", error);
      return "";
    }
  }
  async shareNote(title, content, sourceId, customCss, noIndex = false, shareId) {
    const url = `${this.settings.apiUrl}/api/share`;
    const requestBody = {
      title,
      content,
      sourceId,
      expiresInDays: this.settings.defaultExpiry > 0 ? this.settings.defaultExpiry : null,
      noIndex
    };
    if (shareId) {
      requestBody.shareId = shareId;
    }
    if (customCss && customCss.trim()) {
      requestBody.customCss = customCss;
    }
    try {
      const response = await fetch(url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify(requestBody)
      });
      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(
          `HTTP ${response.status}: ${errorText || response.statusText}`
        );
      }
      return await response.json();
    } catch (error) {
      console.error("SharePlugin: API request failed", error);
      throw error;
    }
  }
  async updateNoteFrontmatter(file, shareUrl, isPrivate, shareId) {
    try {
      await this.app.fileManager.processFrontMatter(file, (frontmatter) => {
        frontmatter.share_url = shareUrl;
        frontmatter.share_mode = isPrivate ? "private \u{1F512}" : "public \u{1F513}";
        if (shareId) {
          frontmatter.share_id = shareId;
        }
      });
    } catch (error) {
      console.error("SharePlugin: Failed to update frontmatter", error);
      new import_obsidian.Notice("\u0421\u0441\u044B\u043B\u043A\u0430 \u0441\u043E\u0437\u0434\u0430\u043D\u0430, \u043D\u043E \u043D\u0435 \u0443\u0434\u0430\u043B\u043E\u0441\u044C \u043E\u0431\u043D\u043E\u0432\u0438\u0442\u044C \u043C\u0435\u0442\u0430\u0434\u0430\u043D\u043D\u044B\u0435 \u0437\u0430\u043C\u0435\u0442\u043A\u0438");
    }
  }
  startAutoSync() {
    this.autoSyncInterval = window.setInterval(
      () => this.autoUpdateAllNotes(),
      60 * 60 * 1e3
    );
    this.registerInterval(this.autoSyncInterval);
  }
  async updateCurrentNote() {
    var _a, _b, _c;
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian.Notice("\u041E\u0442\u043A\u0440\u043E\u0439\u0442\u0435 \u0437\u0430\u043C\u0435\u0442\u043A\u0443 \u0434\u043B\u044F \u043E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0438\u044F");
      return;
    }
    const cache = this.app.metadataCache.getFileCache(activeFile);
    const shareUrl = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.share_url;
    const shareMode = (_b = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _b.share_mode;
    const existingShareId = (_c = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _c.share_id;
    if (!shareUrl) {
      new import_obsidian.Notice('\u042D\u0442\u0430 \u0437\u0430\u043C\u0435\u0442\u043A\u0430 \u043D\u0435 \u043E\u043F\u0443\u0431\u043B\u0438\u043A\u043E\u0432\u0430\u043D\u0430. \u0418\u0441\u043F\u043E\u043B\u044C\u0437\u0443\u0439\u0442\u0435 "\u041E\u043F\u0443\u0431\u043B\u0438\u043A\u043E\u0432\u0430\u0442\u044C \u0437\u0430\u043C\u0435\u0442\u043A\u0443".');
      return;
    }
    const isPrivate = typeof shareMode === "string" && shareMode.includes("private");
    try {
      new import_obsidian.Notice("\u041E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0438\u0435 \u0441\u0442\u0430\u0442\u044C\u0438...");
      let content = await this.app.vault.read(activeFile);
      const title = activeFile.basename;
      const sourceId = activeFile.path;
      content = await this.processImages(content, activeFile);
      const response = await this.shareNote(title, content, sourceId, void 0, isPrivate, existingShareId);
      if (response.success) {
        await this.updateNoteFrontmatter(activeFile, response.url, isPrivate, response.id);
        new import_obsidian.Notice(`\u0421\u0442\u0430\u0442\u044C\u044F \u043E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0430: ${response.url}`, 3e3);
      }
    } catch (error) {
      const msg = error instanceof Error ? error.message : "\u041D\u0435\u0438\u0437\u0432\u0435\u0441\u0442\u043D\u0430\u044F \u043E\u0448\u0438\u0431\u043A\u0430";
      new import_obsidian.Notice(`\u041E\u0448\u0438\u0431\u043A\u0430 \u043E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0438\u044F: ${msg}`, 5e3);
    }
  }
  async autoUpdateAllNotes() {
    var _a, _b, _c;
    const files = this.app.vault.getMarkdownFiles();
    let updated = 0;
    let errors = 0;
    for (const file of files) {
      const cache = this.app.metadataCache.getFileCache(file);
      const shareUrl = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.share_url;
      if (!shareUrl)
        continue;
      const shareMode = (_b = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _b.share_mode;
      const existingShareId = (_c = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _c.share_id;
      const isPrivate = typeof shareMode === "string" && shareMode.includes("private");
      try {
        let content = await this.app.vault.read(file);
        const title = file.basename;
        const sourceId = file.path;
        content = await this.processImages(content, file);
        const response = await this.shareNote(title, content, sourceId, void 0, isPrivate, existingShareId);
        if (response.success) {
          await this.updateNoteFrontmatter(file, response.url, isPrivate, response.id);
          updated++;
        }
      } catch (e) {
        errors++;
      }
    }
    if (updated > 0 || errors > 0) {
      new import_obsidian.Notice(`\u041E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u043E: ${updated}, \u043E\u0448\u0438\u0431\u043E\u043A: ${errors}`, 3e3);
    }
  }
  async syncSharedNotes() {
    var _a;
    new import_obsidian.Notice("\u041F\u0440\u043E\u0432\u0435\u0440\u043A\u0430 \u0441\u0442\u0430\u0442\u0443\u0441\u043E\u0432 \u0441\u0442\u0430\u0442\u0435\u0439...");
    const files = this.app.vault.getMarkdownFiles();
    let cleaned = 0;
    let checked = 0;
    for (const file of files) {
      const cache = this.app.metadataCache.getFileCache(file);
      const shareUrl = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.share_url;
      if (!shareUrl)
        continue;
      checked++;
      const pathSegment = shareUrl.split("/s/").pop();
      if (!pathSegment)
        continue;
      try {
        const res = await fetch(
          `${this.settings.apiUrl}/api/share/${pathSegment}/meta`
        );
        if (res.status === 404 || res.status === 410) {
          await this.app.fileManager.processFrontMatter(file, (fm) => {
            delete fm.share_url;
            delete fm.share_mode;
          });
          cleaned++;
        }
      } catch (e) {
      }
    }
    if (cleaned > 0) {
      new import_obsidian.Notice(`\u041E\u0447\u0438\u0449\u0435\u043D\u043E ${cleaned} \u0438\u0437 ${checked} \u0437\u0430\u043C\u0435\u0442\u043E\u043A`, 5e3);
    } else {
      new import_obsidian.Notice(`\u041F\u0440\u043E\u0432\u0435\u0440\u0435\u043D\u043E ${checked} \u0437\u0430\u043C\u0435\u0442\u043E\u043A, \u0432\u0441\u0435 \u0430\u043A\u0442\u0443\u0430\u043B\u044C\u043D\u044B`, 3e3);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  onunload() {
    if (this.autoSyncInterval !== null) {
      window.clearInterval(this.autoSyncInterval);
    }
    console.log("Share Plugin unloaded");
  }
};
var ShareSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 \u043F\u0443\u0431\u043B\u0438\u043A\u0430\u0446\u0438\u0438 \u0437\u0430\u043C\u0435\u0442\u043E\u043A" });
    new import_obsidian.Setting(containerEl).setName("URL API \u0441\u0435\u0440\u0432\u0435\u0440\u0430").setDesc("\u0410\u0434\u0440\u0435\u0441 \u0432\u0430\u0448\u0435\u0433\u043E \u0441\u0435\u0440\u0432\u0435\u0440\u0430 (\u043D\u0430\u043F\u0440\u0438\u043C\u0435\u0440: https://your-server.example.com)").addText(
      (text) => text.setPlaceholder("https://your-server.example.com").setValue(this.plugin.settings.apiUrl).onChange(async (value) => {
        this.plugin.settings.apiUrl = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u0410\u0432\u0442\u043E\u043C\u0430\u0442\u0438\u0447\u0435\u0441\u043A\u0438 \u043A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u0441\u0441\u044B\u043B\u043A\u0443").setDesc("\u041A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u0441\u0441\u044B\u043B\u043A\u0443 \u0432 \u0431\u0443\u0444\u0435\u0440 \u043E\u0431\u043C\u0435\u043D\u0430 \u043F\u043E\u0441\u043B\u0435 \u043F\u0443\u0431\u043B\u0438\u043A\u0430\u0446\u0438\u0438").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoClipboard).onChange(async (value) => {
        this.plugin.settings.autoClipboard = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u0421\u0440\u043E\u043A \u0436\u0438\u0437\u043D\u0438 \u0441\u0441\u044B\u043B\u043A\u0438 (\u0434\u043D\u0438)").setDesc("\u0427\u0435\u0440\u0435\u0437 \u0441\u043A\u043E\u043B\u044C\u043A\u043E \u0434\u043D\u0435\u0439 \u0443\u0434\u0430\u043B\u0438\u0442\u044C \u0437\u0430\u043C\u0435\u0442\u043A\u0443 (0 = \u043D\u0438\u043A\u043E\u0433\u0434\u0430)").addText(
      (text) => text.setPlaceholder("0").setValue(String(this.plugin.settings.defaultExpiry)).onChange(async (value) => {
        const num = parseInt(value);
        if (!isNaN(num) && num >= 0) {
          this.plugin.settings.defaultExpiry = num;
          await this.plugin.saveSettings();
        }
      })
    );
  }
};
